# Generated by Django 4.2.1 on 2023-06-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avataruser',
            options={'ordering': ('pk',), 'verbose_name': 'Аватар пользователя', 'verbose_name_plural': 'Аватары пользователей'},
        ),
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ('pk',), 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(default='Неизвестно', max_length=64, verbose_name='Email-адрес'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='fullName',
            field=models.CharField(default='Неизвестно', max_length=64, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(default='Неизвестно', max_length=32, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
