# Generated by Django 4.2.1 on 2023-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
